<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h3_How to make it</name>
   <tag></tag>
   <elementGuidId>04781919-1dda-4811-8547-2a876cbae714</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//h3[@id='how-to-make-it']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#how-to-make-it</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>6c97f375-384c-433e-bc9c-f640f67e707b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>how-to-make-it</value>
      <webElementGuid>e6d60a90-ab50-4cbe-b5dc-89e3235d9bae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>How to make it:</value>
      <webElementGuid>fc5c2149-afb5-4464-b232-b929e4e03fd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;how-to-make-it&quot;)</value>
      <webElementGuid>d035ab73-269c-4809-9e81-9762dfbd3e06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_MelonEats  Streamlit/iframe__iframe_nim44_26</value>
      <webElementGuid>beabf717-4773-468c-ae12-fa6ef21baf32</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h3[@id='how-to-make-it']</value>
      <webElementGuid>a887faf1-208d-494f-8b32-5660fd54ef40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/section/div/div/div/div/div[7]/div/div/div/div[2]/div/div/div/div/div/div/div/h3</value>
      <webElementGuid>9204a73a-ab98-41dc-9d5f-8c6b4632aafa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ingredients:'])[1]/following::h3[1]</value>
      <webElementGuid>4bb3b765-60cc-49f3-aaa8-40ec885d26cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Servings:'])[1]/following::h3[1]</value>
      <webElementGuid>65b47bb9-9c07-4ed1-91fd-c771224724b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Steps:'])[1]/preceding::h3[1]</value>
      <webElementGuid>2ee8cf2e-b987-42fe-add9-50a13a19a22e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='How to make it:']/parent::*</value>
      <webElementGuid>391b8ee3-bb77-4a13-b204-2cf268122ae1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/div/div/h3</value>
      <webElementGuid>f50141bb-1fa0-4f6c-a728-7b4c64a225b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[@id = 'how-to-make-it' and (text() = 'How to make it:' or . = 'How to make it:')]</value>
      <webElementGuid>c1cc0e38-def6-4b2b-a98f-519f0b775601</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
