<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe__iframe_nim44_26</name>
   <tag></tag>
   <elementGuidId>eff8d8a1-cb1e-4ee2-9b3e-b90d9de50640</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/iframe</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe._iframe_nim44_26</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>bc8f118a-e6ac-43b7-a5af-418dc6e66c3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allow</name>
      <type>Main</type>
      <value>accelerometer; ambient-light-sensor; autoplay; battery; camera; clipboard-write; document-domain; encrypted-media; fullscreen; geolocation; gyroscope; layout-animations; legacy-image-formats; magnetometer; microphone; midi; oversized-images; payment; picture-in-picture; publickey-credentials-get; sync-xhr; usb; vr ; wake-lock; xr-spatial-tracking</value>
      <webElementGuid>7c418f2c-1ddc-44f9-a2a3-143d2952eb10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-modals allow-popups allow-popups-to-escape-sandbox allow-same-origin allow-scripts allow-downloads</value>
      <webElementGuid>c57e0826-947d-4aa1-9f46-7e2f778ed500</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>7d21c699-d09a-4b9c-a1db-2083210d556b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>streamlitApp</value>
      <webElementGuid>c3d1baee-533e-4979-ba01-ddaba7e1cd6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>//meloneats.streamlit.app/~/+/</value>
      <webElementGuid>c6abc0b3-8452-47a4-84dc-f937b0b84748</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_iframe_nim44_26</value>
      <webElementGuid>ad46efa7-4624-4be7-9376-ffd327288c83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;_streamlitAppContainer_nim44_1&quot;]/div[@class=&quot;_stateContainer_nim44_26&quot;]/iframe[@class=&quot;_iframe_nim44_26&quot;]</value>
      <webElementGuid>77c4dca5-8e54-41d6-b5bc-1ca29853b205</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/iframe</value>
      <webElementGuid>d4d8ea7e-92c2-46a5-9df7-a7b22833963c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>59b5dd08-1489-4c4d-84e8-bfc5b0de972f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'streamlitApp' and @src = '//meloneats.streamlit.app/~/+/']</value>
      <webElementGuid>824ae82e-38cc-4473-9790-824265f9818a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
