<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Press Enter to apply_number_input_1</name>
   <tag></tag>
   <elementGuidId>35bd8385-0510-4fb8-8a6b-05ca74d9af02</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='number_input_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[id^=&quot;number_input&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>598e300a-4089-4f03-a4b9-27778a92be12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Number of recipes to show:</value>
      <webElementGuid>d277468a-a5a4-472e-a83a-989cc272a312</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>368e6460-3f4d-4587-ae43-a62e102715cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6020c653-db13-4e7e-9bce-810ea506e5c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>4357b287-3e27-44d0-987e-88670cce2c41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>number_input_1</value>
      <webElementGuid>7dc84aef-e74d-40ba-b95d-82f30e230ba1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>a1020cf5-e821-4330-aa80-6d841fa00790</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>286a1cd1-68c2-4e92-b99f-428e3986190d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>525f89cb-5a35-49f8-82e8-ca38112458d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>24baa694-7906-487b-aa92-50e578ef7b9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>stNumberInputField</value>
      <webElementGuid>23839313-678c-481b-8a4e-e1a1c13700ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>st-ae st-bc st-ai st-aj st-ak st-al st-bd st-be st-bf st-bg st-bh st-ah st-bi st-bj st-bk st-bl st-bm st-bn st-bo st-bp st-ax st-ay st-az st-bq st-b1 st-b2 st-bb st-br st-bs</value>
      <webElementGuid>286f35e9-a028-4536-9f0e-8c9df5bc5e8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>326f6937-d47b-428b-a8dc-4bb68a22bdb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;number_input_1&quot;)</value>
      <webElementGuid>2a224cd1-cbc3-449c-846a-040ecc138cd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_MelonEats  Streamlit/iframe__iframe_nim44_26</value>
      <webElementGuid>b9ff3aef-40c5-46af-90d7-7a0fb4f0a9f1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='number_input_1']</value>
      <webElementGuid>1982732a-cd95-4cf0-9876-a24a7f25d96e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/section/div/div/div/div/div[4]/div/div/div/div/input</value>
      <webElementGuid>c5ce2ddd-5e45-45aa-9a70-6c72dacce54b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/input</value>
      <webElementGuid>b57ca151-0378-4959-930b-3f5ece0120a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'number_input_1' and @type = 'number']</value>
      <webElementGuid>9fbdb904-e9e7-4dbe-ae54-9881a0beba21</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
