<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_MelonEats - Recipe Finder_text_input_2</name>
   <tag></tag>
   <elementGuidId>af5ef322-25fa-4f51-a210-e30a281064a8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[starts-with(@id, &quot;text_input&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[id^=&quot;text_input&quot;</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9b9998e6-f87d-465f-bfb2-dfb5f1db8224</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Enter the ingredients that you have (e.g., chicken, chili, cheese, beef, pasta):</value>
      <webElementGuid>3a02b5d8-c3b6-49e7-8f75-9144783882eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>dfb36159-5968-4451-8840-adb1e932afa5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>38e0c52b-f217-44ee-a876-ad7260478c42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text_input_2</value>
      <webElementGuid>9f2dfae4-e3b5-4e2e-b9fd-99808345ff3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9beb6e6b-0638-47bc-bafb-5639234cc522</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>444fdb8e-9bb6-482c-ba69-461f18874213</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>st-ae st-bc st-ai st-aj st-ak st-al st-bd st-be st-bf st-bg st-bh st-ah st-bi st-bj st-bk st-bl st-bm st-bn st-bo st-bp st-ax st-ay st-az st-bq st-b1 st-b2 st-bb st-br st-bs st-c1</value>
      <webElementGuid>767f8590-43eb-4e81-a585-b6f0bf339531</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text_input_2&quot;)</value>
      <webElementGuid>c16c4232-9f98-4591-876a-502501bf56c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_MelonEats  Streamlit/iframe__iframe_nim44_26</value>
      <webElementGuid>b3b8e3af-9978-431e-a3d2-0899bffdc2cb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[starts-with(@id, &quot;text_input&quot;]</value>
      <webElementGuid>e0950c72-71ab-4783-a971-d6cdd691e05a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/section/div/div/div/div/div[3]/div/div/div/input</value>
      <webElementGuid>1195c09a-4153-427c-a262-ecc435928586</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>4fe6ab19-e725-4062-a91e-52cd8b8a9a88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'text_input_2' and @type = 'text']</value>
      <webElementGuid>54d9aaa2-be94-438a-a208-470cee57b47a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
